# Generated by Django 4.1.7 on 2023-04-07 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_comment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
