# Generated by Django 4.2 on 2023-04-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0003_comment_createddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
